executionFrameworkSpec:
  name: standalone
jobType: SegmentCreationAndUpload
inputDirURI: 'file:///pinot-samples/airline_stats/data'
includeFileNamePattern: 'glob:**/*.json'
outputDirURI: 'file:///tmp/pinot-airlineStats'
overwriteOutput: true
segmentCreationJobSpec:
  inputFormat: json
  schemaFile: 'file:///pinot-samples/airline_stats/schema.json'
  tableConfigFile: 'file:///pinot-samples/airline_stats/table.json'
  recordReaderSpec:
    className: org.apache.pinot.plugin.inputformat.json.JSONRecordReader
    configClassName: org.apache.pinot.plugin.inputformat.json.JSONRecordReaderConfig
segmentPushJobSpec:
  tableName: airlineStats
  controllerURI: 'http://pinot-controller:9000'
